/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_elvin_unit3_jni_JniTest */

#ifndef _Included_com_example_elvin_unit3_jni_JniTest
#define _Included_com_example_elvin_unit3_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_elvin_unit3_jni_JniTest
 * Method:    strFromJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_elvin_unit3_jni_JniTest_strFromJni
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
