/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_elvin_unit3_TestInterface */

#ifndef _Included_com_example_elvin_unit3_TestInterface
#define _Included_com_example_elvin_unit3_TestInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_elvin_unit3_TestInterface
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_elvin_unit3_TestInterface_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_elvin_unit3_TestInterface
 * Method:    showStringFromJave
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_elvin_unit3_TestInterface_showStringFromJave
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
