/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_elvin_unit3_jni_JniTest */

#ifndef _Included_com_example_elvin_unit3_jni_JniTest
#define _Included_com_example_elvin_unit3_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_elvin_unit3_jni_JniTest
 * Method:    strFromJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_elvin_unit3_jni_JniTest_strFromJni
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_elvin_unit3_jni_JniTest
 * Method:    testString
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_elvin_unit3_jni_JniTest_testString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_elvin_unit3_jni_JniTest
 * Method:    sumNumber
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_example_elvin_unit3_jni_JniTest_sumNumber
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_elvin_unit3_jni_JniTest
 * Method:    controlPointOfArray
 * Signature: ([II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_elvin_unit3_jni_JniTest_controlPointOfArray
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_example_elvin_unit3_jni_JniTest
 * Method:    testThrowExecption
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_elvin_unit3_jni_JniTest_testThrowExecption
  (JNIEnv *, jobject);

/*
 * Class:     com_example_elvin_unit3_jni_JniTest
 * Method:    getFiledFromJava
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_elvin_unit3_jni_JniTest_getFiledFromJava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
