/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_elvin_unit5_jni_TestJni */

#ifndef _Included_com_example_elvin_unit5_jni_TestJni
#define _Included_com_example_elvin_unit5_jni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_elvin_unit5_jni_TestJni
 * Method:    startToShowLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_elvin_unit5_jni_TestJni_startToShowLog
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
