/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_elvin_unit7_jni_JniOperatiton */

#ifndef _Included_com_example_elvin_unit7_jni_JniOperatiton
#define _Included_com_example_elvin_unit7_jni_JniOperatiton
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_elvin_unit7_jni_JniOperatiton
 * Method:    nativeInt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_elvin_unit7_jni_JniOperatiton_nativeInt
  (JNIEnv *, jobject);

/*
 * Class:     com_example_elvin_unit7_jni_JniOperatiton
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_elvin_unit7_jni_JniOperatiton_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     com_example_elvin_unit7_jni_JniOperatiton
 * Method:    nativeWorker
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_elvin_unit7_jni_JniOperatiton_nativeWorker
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
