/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_elvin_unit12_BitmapPlayerActivity */

#ifndef _Included_com_example_elvin_unit12_BitmapPlayerActivity
#define _Included_com_example_elvin_unit12_BitmapPlayerActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_elvin_unit12_BitmapPlayerActivity
 * Method:    render
 * Signature: (JLandroid/graphics/Bitmap;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_elvin_unit12_BitmapPlayerActivity_render
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
