/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_elvin_unit2_TestJni2 */

#ifndef _Included_com_example_elvin_unit2_TestJni2
#define _Included_com_example_elvin_unit2_TestJni2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_elvin_unit2_TestJni2
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_elvin_unit2_TestJni2_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_elvin_unit2_TestJni2
 * Method:    intFromJni
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_elvin_unit2_TestJni2_intFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
