/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_elvin_unit2_TestJni */

#ifndef _Included_com_example_elvin_unit2_TestJni
#define _Included_com_example_elvin_unit2_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_elvin_unit2_TestJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_elvin_unit2_TestJni_stringFromJNI
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL
Java_com_example_elvin_unit2_TestJni_intfromJNI(JNIEnv *env, jobject instance);

#ifdef __cplusplus
}
#endif
#endif
