/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_elvino_unit8_MainActivity */

#ifndef _Included_com_example_elvino_unit8_MainActivity
#define _Included_com_example_elvino_unit8_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_elvino_unit8_MainActivity
 * Method:    nativeStartTcpServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_elvino_unit8_MainActivity_nativeStartTcpServer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_elvino_unit8_MainActivity
 * Method:    nativeStartUdpServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_elvino_unit8_MainActivity_nativeStartUdpServer
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
