/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_elvin_unit8_jni_JniOperation */

#ifndef _Included_com_example_elvin_unit8_jni_JniOperation
#define _Included_com_example_elvin_unit8_jni_JniOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_elvin_unit8_jni_JniOperation
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_elvin_unit8_jni_JniOperation_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
